services:
  backend:
    image: olvanotjeanclaude/epin-backend:latest
    container_name: laravel-app
    expose:
      - "9000"
    restart: unless-stopped

  socket:
    image: olvanotjeanclaude/epin-socket:latest
    container_name: socket-server
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    image: olvanotjeanclaude/epin-frontend:latest
    container_name: next-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/aws.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
      - socket
    restart: unless-stopped
